# -*- coding: utf-8 -*-
"""ejercicios

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fbCvUjqZtIxR5mhX7awTWF9D5gnnIuXl
"""

import streamlit as st
st.write("Hello, *World!* :sunglasses: ")